# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-20 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iniita', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='cardcaregory',
            new_name='card_caregory',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='cardtag',
            new_name='card_tag',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='category',
            new_name='request_category',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='tag',
            new_name='request_tag',
        ),
        migrations.RemoveField(
            model_name='card',
            name='carddate',
        ),
        migrations.RemoveField(
            model_name='request',
            name='date',
        ),
    ]
