# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-22 01:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iniita', '0004_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='detail',
            new_name='content',
        ),
    ]
