# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-22 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iniita', '0007_auto_20180122_1356'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
