# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-25 18:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iniita', '0009_auto_20180125_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='cardtitle',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='card',
            name='user',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='user',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
