# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-25 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iniita', '0010_auto_20180126_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='liked',
            field=models.IntegerField(default=0),
        ),
    ]
